language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - pip install flake8 --use-mirrors
  - pip install -q -e . --use-mirrors
before_script:
  - flake8 figo
script:
  - python setup.py test
