language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - pip install coveralls --use-mirrors
  - pip install -q -e . --use-mirrors
script: coverage run setup.py test
after_success:
  - coveralls